[tool.bumpversion]
current_version = "0.0.1"
message = "Bump version of dialogue-manager: {current_version} â†’ {new_version}"
commit = false
tag = false
tag_name = "agents/dialogue-manager-v{new_version}"

[[tool.bumpversion.files]]
filename = "pyproject.toml"
search = "version = \"{current_version}\""
replace = "version = \"{new_version}\""